### PR TITLE
Update the components select when a product is selected

### PR DESCRIPTION
**Pull request by Ayushsunny**
---

**Description**
Updated  the components select when a product is selected in #2240 

**I have tested this PR on**

  

 Linux/Ubuntu

**code?**
``` JavaScript
  options["products"].callback = async function () { 
    await buildProductsSelect(new Set(getOption("products"))); 
    return "components"; 
  }; ```

### CODE REVIEW

**Comment by Ayushsunny** [comment]
> @Ayushsunny this won't work (did you test it?). You're re-building the products select when a component is selected, but we actually want to do the opposite (also you're calling `buildProductsSelect` with an argument, but `buildProductsSelect` doesn't take any argument as input).
> 
> Try applying the changes I suggested in [#2240 (comment)](https://github.com/mozilla/bugbug/issues/2240#issuecomment-802912548).

sorry I'm not able to get, what do you trying to explain in this ? https://github.com/mozilla/bugbug/issues/2240#issuecomment-802912548 
could you explain bit more or like exact what changes I've to do, please

**Comment by marco-c** [comment]
What parts of the comment are unclear for you?

**Comment by Ayushsunny** [comment]
> What parts of the comment are unclear for you?

This line sir : "by adding a product argument, and using it like the teams argument to filter the bug summaries.
Next, you will need to something like"

**Comment by marco-c** [comment]
You need to add an additional argument to the `buildComponentsSelect` function I mentioned, the argument will be called `products`, and you will use it similarly to the already existing `teams` argument.

**Comment by Ayushsunny** [comment]
> You need to add an additional argument to the `buildComponentsSelect` function I mentioned, the argument will be called `products`, and you will use it similarly to the already existing `teams` argument.

Yes but did right in this code?
``` Javascript 
 options["products"].callback = async function () { 
    await buildProductsSelect(new Set(getOption("products"))); 
    return "components"; 
  }; ```

what changes do I have to perform in this code like changing this "buildPRoductselect" to "buildComponentselect" ?

**Comment by marco-c** [comment]
No @Ayushsunny, sorry. You didn't do any of the things I said in the comment above :)

**Comment by Ayushsunny** [comment]
> No @Ayushsunny, sorry. You didn't do any of the things I said in the comment above :)

Sorry, but I really not able to get you? either explain me clearly or assign anyone else

**Comment by marco-c** [comment]
@Ayushsunny unfortunately I'm not able to explain it more clearly than that.

**Comment by Ayushsunny** [comment]
> @Ayushsunny unfortunately I'm not able to explain it more clearly than that.

Okay, and Thank you so much for your earlier help sir.
sorry

**Pull request closed without merging**
