### PR TITLE
Updated the appropriate % operator for logging statements

### LINKED ISSUE #3837: Some logging statements don't use the appropriate % operator
> This is a valid fix but unrelated to the goal of this PR. We could open a new issue and fix it in a separate PR (with similar cases if there are any)

_Originally posted by @suhaibmujahid in https://github.com/mozilla/bugbug/pull/3822#discussion_r1398670853_

### PR DESCRIPTION
**Pull request by wittyicon29**
Fixed #3837 

Updated the operator to %0.2f instead of %d for the logging statements.

### CODE REVIEW

**Comment by suhaibmujahid** [comment]
Thank you, @wittyicon29! Did you check if other cases need to be fixed?

**Comment by wittyicon29** [comment]
I haven't actually, if it would be okay I'll check right away. 
For any changes made, should a new PR be created?

**Comment by wittyicon29** [comment]
@suhaibmujahid I've checked for the other cases, but aren't any.

**Review by suhaibmujahid — APPROVED** [review]
> I haven't actually, I'll check right away. For any changes made, should a new PR be created?

Since it is within the scope of the same issue. There is no need for a new PR.


> I've checked for the other cases, but aren't any.

Thank you!

**Pull request merged**
