### PR TITLE
log spam/non-spam bugs in SpamBug get_labels

### PR DESCRIPTION
**Pull request by Pranay144**
Please guide me if any changes needed.

### CODE REVIEW

**Comment by abhaykatheria** [comment]
Hey man, you failed the lint test just look into it so yo pass all the test.
pip install flake8,black and pylint and use them u will pass all the test..:)

**Comment by marco-c** [comment]
@Pranay144 why did you close the PR? Do you still want to work on this?

**Comment by Pranay144** [comment]
@marco-c I'm sorry for closing PR without informing.
I am working on it and am sending another pull request ASAP.

**Comment by marco-c** [comment]
@Pranay144 you don't need to close a PR and reopen a new one for every required change, you can just update an already existing PR.

**Comment by Pranay144** [comment]
@marco-c I deleted my mozilla/bugbug fork for some reason,
I forked it again, so i have to open new PR!

**Comment by Pranay144** [comment]
Also i am running pre-commit and it's not letting me commit the changes.
It says **hookid: check-executables-have-shebangs.......failed**
what should i do?

**Comment by marco-c** [comment]
Can you copy the entire pre-commit message?

**Comment by Pranay144** [comment]
`seed isort known_third_party.............................................Passed
isort....................................................................Passed
black....................................................................Passed
flake8...................................................................Passed
Check python ast.........................................................Passed
Check docstring is first.................................................Passed
Check that executables have shebangs.....................................Failed
hookid: check-executables-have-shebangs

bugbug/models/spambug.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: chmod -x bugbug/models/spambug.py
  If it is supposed to be executable, double-check its shebang.

Check for merge conflicts................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Debug Statements (Python)................................................Passed
Trim Trailing Whitespace.................................................Passed
Check Yaml...........................................(no files to check)Skipped
Mixed line ending........................................................Passed
Tests should end in _test.py.........................(no files to check)Skipped
Check JSON...........................................(no files to check)Skipped
Fix requirements.txt.................................(no files to check)Skipped
codespell................................................................Passed
taskcluster_yml......................................(no files to check)Skipped
Strip unnecessary `# noqa`s..............................................Passed
mypy.....................................................................Passed
Check for useless excludes...........................(no files to check)Skipped
[INFO] Restored changes from C:\Users\ACER/.cache\pre-commit\patch1578042919.`

**Comment by marco-c** [comment]
It means you somehow set bugbug/models/spambug.py to be executable, while it shouldn't be. You'll need to make it non-executable.

**Comment by Pranay144** [comment]
@marco-c I am sorry but it is still failing the same.
```
$ ls -l spambug.py
-rw-r--r-- 1 ACER 197121 3929 Jan  3 08:42 spambug.py
```
and spambug.py is not executable!

**Comment by marco-c** [comment]
Please file an issue on https://github.com/pre-commit/pre-commit-hooks/issues (similar to https://github.com/pre-commit/pre-commit-hooks/issues/361) to explain your problem, they'll be able to help.

For now, simply commit with the "--no-verify" option to skip the check.

**Comment by Pranay144** [comment]
I did this
```
SKIP=ckeck-executables-have-shebangs git commit
```
all the other checks are passed.

**Comment by abhaykatheria** [comment]
@Pranay144 try this 

chmod u=rw,g=r,o=r spambug.py

i dont know but you can try this maybe this will work

**Pull request closed without merging**
