### PR TITLE
Include `filed_via` field and bug feature.

### PR DESCRIPTION
**Pull request by jpangas**
This PR is a patch that includes the `filed_via` field. It also includes the field among the bug features in `bug_features.py`

### CODE REVIEW

**Comment by jpangas** [comment]
I think some of the tests are expected to fail.

**Comment by suhaibmujahid** [comment]
> I think some of the tests are expected to fail.

Tests should not fail because we did not use the feature yet.

**Review by suhaibmujahid — APPROVED** [review]
Thank you, @jpangas! LGTM.

**Comment by jpangas** [comment]
> > I think some of the tests are expected to fail.
> 
> Tests should not fail because we did not use the feature yet.

Oh, nice! I will be eager to test the feature in `spam_bug.py` Thanks @suhaibmujahid

**Pull request merged**
