### PR TITLE
post-patch

### LINKED ISSUE #1718: Define an API to select tests POSTing the contents of a patch
This way we can:
1) Start the test selection jobs even earlier than now (currently we start them after a Mercurial push);
2) Run the selector locally without a push to try (to select tests to run locally).

### PR DESCRIPTION
**Pull request by anooptp**
Fixes #1718

### CODE REVIEW

**Comment by anooptp** [comment]
@marco-c - Could you please provide your inputs.

**Comment by marco-c** [comment]
Sorry I was on holidays. It looks reasonable so far. Did you manage to test it to see that the data was passed correctly to the `apply_patch` function?

**Comment by anooptp** [comment]
> Sorry I was on holidays. It looks reasonable so far. Did you manage to test it to see that the data was passed correctly to the `apply_patch` function?

yes, I can see that the value is getting passed.

image

**Comment by anooptp** [comment]
Any specific format in which patch data needs to be passed?

**Comment by marco-c** [comment]
> Any specific format in which patch data needs to be passed?

It can be plain text

**Comment by marco-c** [comment]
> > Sorry I was on holidays. It looks reasonable so far. Did you manage to test it to see that the data was passed correctly to the `apply_patch` function?
> 
> yes, I can see that the value is getting passed.
> 
> image

What you're showing is the log from https://github.com/mozilla/bugbug/pull/2679/files#diff-ca8f2b585c0d22a63ede5aea635f3266fcf60181a7e6cd395c6a3e49916beda7R842.
Is the data also arriving on the worker side, at https://github.com/mozilla/bugbug/pull/2679/files#diff-cf49a1f79f836b960b0e15cc583bf3e73016b7c7e3d0e13398ddc35d004a3fa8R244?

**Comment by anooptp** [comment]
> > > Sorry I was on holidays. It looks reasonable so far. Did you manage to test it to see that the data was passed correctly to the `apply_patch` function?
> > 
> > 
> > yes, I can see that the value is getting passed.
> 
> What you're showing is the log from https://github.com/mozilla/bugbug/pull/2679/files#diff-ca8f2b585c0d22a63ede5aea635f3266fcf60181a7e6cd395c6a3e49916beda7R842. Is the data also arriving on the worker side, at https://github.com/mozilla/bugbug/pull/2679/files#diff-cf49a1f79f836b960b0e15cc583bf3e73016b7c7e3d0e13398ddc35d004a3fa8R244?

worker node is taking a lot of time to come up. So, not able to test it locally. Is there any alternative way to test it.

image

image

**Comment by suhaibmujahid** [comment]
Closing for lack of updates, feel free to reopen if you still intend to work on this.

**Pull request closed without merging**
