### PR TITLE
Issue #3692: Modified methods to use `zstdmt` binary

### LINKED ISSUE #3692: Use all threads when decompressing with zstd
We should use the `-T0` option (or use the `zstdmt` binary instead of `zstd`).

### PR DESCRIPTION
**Pull request by PromiseFru**
Closes #3692

Hello @marco-c @suhaibmujahid,

I've made changes to the `zstd_decompress` and `extract_tar_zst` methods. They now use the `zstdmt` binary instead of the `zstd` binary for decompression tasks. 

Please, I wish to find out if this change is needed just for decompression tasks, or should I update other methods like `zstd_compress` and `create_tar_zst` that use the `zstd` binary for compression.

Additionally, I noticed the presence of the `zstandard` Python library, alongside the use of the `zstd` binary for certain tasks. I'm curious about why both are used when they seem to perform similar tasks.

### CODE REVIEW

**Comment by PromiseFru** [comment]
fixes: #3692

**Comment by suhaibmujahid** [comment]
Thank you for the PR, @PromiseFru! Could you please test/execute the change code locally to confirm that it is working?


> Closes #3692

Please add the linking keyword in the description 



>Please, I wish to find out if this change is needed just for decompression tasks, or should I update other methods like zstd_compress and create_tar_zst that use the zstd binary for compression.

The scope of the issue concerns the decompression tasks only.



> Additionally, I noticed the presence of the zstandard Python library, alongside the use of the zstd binary for certain tasks. I'm curious about why both are used when they seem to perform similar tasks.

Originally `zstandard` was used everywhere but it was replaced to improve the performance.

**Comment by PromiseFru** [comment]
> Thank you for the PR, @PromiseFru! Could you please test/execute the change code locally to confirm that it is working?
> 
> > Closes #3692
> 
> Please add the linking keyword in the description
> 
> > Please, I wish to find out if this change is needed just for decompression tasks, or should I update other methods like zstd_compress and create_tar_zst that use the zstd binary for compression.
> 
> The scope of the issue concerns the decompression tasks only.
> 
> > Additionally, I noticed the presence of the zstandard Python library, alongside the use of the zstd binary for certain tasks. I'm curious about why both are used when they seem to perform similar tasks.
> 
> Originally `zstandard` was used everywhere but it was replaced to improve the performance.

Hello @suhaibmujahid 

I ran the tests that focused on the methods I had updated, and all of them passed. I have attached their logs below:

```bash
pytest -vk "test_zstd_compress_decompress"
```
[test_zstd_compress_decompress.txt](https://github.com/mozilla/bugbug/files/12878889/test_zstd_compress_decompress.txt)

```bash
pytest -vk "test_extract_db_zst"
```
[test_extract_db_zst.txt](https://github.com/mozilla/bugbug/files/12878897/test_extract_db_zst.txt)

**Comment by suhaibmujahid** [comment]
Thank you, @PromiseFru! We have now `extract_tar_zst()` still not tested. Could you execute it locally or add a test for it?

BTW. If you add a test, it will run automatically on our CI.

**Review by suhaibmujahid — APPROVED** [review]
Thank you, @PromiseFru! LGTM!

**Comment by marco-c** [comment]
Couldn't `create_tar_zst` also use `zstdmt`?

**Comment by suhaibmujahid** [comment]
> Couldn't `create_tar_zst` also use `zstdmt`?

I advised in https://github.com/mozilla/bugbug/pull/3703#issuecomment-1758860569 to only change the decompressing functions to stay in the scope of issue #3692. I will create a separate issue for that.

**Review by marco-c — APPROVED** [review]
Thanks!

**Pull request merged**
