### PR TITLE
added check for downloaded DB version with current version

### PR DESCRIPTION
**Pull request by avijit1258**
@marco-c I have added the code here. Can you kindly check if I am getting things write?

### CODE REVIEW

**Comment by abhaykatheria** [comment]
```
            with open(f"{os.path.basename(path)}.version", "r") as f:
                current_version = f.read()
```
suppose path was "C:/new1/new2/prova.json"
the current schema existed there and not at os.path.basename(path) ///which is just prova.json

there are cases where files are downloaded in current directory where your code have not given error at some places paths have been specified 
 
and when you extract the downloaded file the earlier prova.json is overwritten by new prova.json
so you are comparing to equal things instead.

p.s.: I am just a beginner so pardon me if i got something wrong and do correct me.
Happy To Help

**Comment by avijit1258** [comment]
@abhaykatheria Thank you for your response. I think you are right. I got that wrong. Can you help me to identify how db.py differentiates the current DB file and the downloaded one? Or I have to create a temp path, download there instead and then replace the DB if the condition applies?

Thanks I highly appreciate your time.
Avijit

**Comment by abhaykatheria** [comment]
Creating a temp directory is the way to go I guess..

**Comment by marco-c** [comment]
See https://github.com/mozilla/bugbug/issues/1108#issuecomment-570610247, this should already be covered by the etag check, so we just need to write a test.

**Pull request closed without merging**
