### PR TITLE
bugzilla.py: Fetching comments, attachments etc via api

### LINKED ISSUE #573: Get bug data all at once instead of attachments and comments separately
Using the feature from https://github.com/mozilla-bteam/bmo/pull/1148.

### PR DESCRIPTION
**Pull request by sladyn98**
Added url to bugzilla.py to get data.
Added data to json conversion.

Fixes #573.

### CODE REVIEW

**Comment by sladyn98** [comment]
@marco-c This PR is ready for review.

**Comment by sladyn98** [comment]
@marco-c Could you elaborate a bit more, since I checked out the api and it only allowed fetching these parameters.

**Comment by marco-c** [comment]
> @marco-c Could you elaborate a bit more, since I checked out the api and it only allowed fetching these parameters.

You are doing:
GET https://bugzilla.mozilla.org/rest/bug/{}
GET https://bugzilla.mozilla.org/rest/bug/{}?include_fields=history,comments,attachments

You should instead do just one request where you get both the bug data and the history, comments and attachments.

**Comment by marco-c** [comment]
Feel free to reopen when you have updates.

**Pull request closed without merging**
