### PR TITLE
Add number of previous commits touching the same files as a feature

### LINKED ISSUE #112: Add number of previous commits touching the same files as a feature

### PR DESCRIPTION
**Pull request by sbeesm**
Fixes #112.

### CODE REVIEW

**Comment by marco-c** [comment]
You'll need to resolve some conflicts before being able to merge.

**Comment by sbeesm** [comment]
> It'd be nice to somehow refactor this to avoid duplicating similar code multiple times

Should we consider calculating commits for both the files and components in just one loop to avoid code duplication?

We can just iterate over files and components separately and the code should still be readable.

**Comment by marco-c** [comment]
> Should we consider calculating commits for both the files and components in just one loop to avoid code duplication?

Yeah, good idea, let's do that!

**Comment by sbeesm** [comment]
Taskcluster linting test fails, and I'm not able to figure out the error from the log.

Could this be a problem on Taskcluster's side?

**Comment by marco-c** [comment]
Try `git fetch --all`, then `git push --tags`. Then, I'll retrigger the taskcluster job.

**Comment by sbeesm** [comment]
> Try `git fetch --all`, then `git push --tags`. Then, I'll retrigger the taskcluster job.

Done!

**Pull request merged**
