### PR TITLE
Modify linting task to only run on modified files

### PR DESCRIPTION
**Pull request by cklyyung**
Addresses issue #298 .
I'm comparing against the master branch of the original repo; `upstream/master...` will compare the original repo to what's currently checked out, from their common ancestor. The `diff-filter` is an exclusive filter, that filters out files that have been deleted.

### CODE REVIEW

**Comment by marco-c** [comment]
I think to be more precise, you could probably use the target branch information from the github event.

**Comment by cklyyung** [comment]
I decided to use `head_rev` instead of `head_branch`, since I would have to add an additional command to fetch the branch from origin.

**Comment by marco-c** [comment]
> I think to be more precise, you could probably use the target branch information from the github event.

This comment still applies.
You are getting all files modified compared to master, but PRs can be against other branches, master is not the only possible target branch.

**Comment by cklyyung** [comment]
For a `github-push` event, I'm grabbing `event.before`. According to the [docs](https://developer.github.com/v3/activity/events/types/#pushevent), this is the most recent commit on the branch before the push. 
I'm not sure if this will be sufficient; consider a case where commit `A` is pushed with a linting error on file `Z`. The check will fail. Then commit `B` is pushed, which only modifies file `Y`, and not file `Z`. The check will succeed, since file `Z` won't be caught in the diff between commits `A` and `B`.
Also, in the original issue, this was suggested as a way to reduce the runtime of the linting task. Looking at the logs, this still runs at around the same time as checking all files.

**Comment by marco-c** [comment]
> I'm not sure if this will be sufficient; consider a case where commit A is pushed with a linting error on file Z. The check will fail. Then commit B is pushed, which only modifies file Y, and not file Z. The check will succeed, since file Z won't be caught in the diff between commits A and B.

This case should never happen, since we never push commits or merge PRs with linting errors.

>  Also, in the original issue, this was suggested as a way to reduce the runtime of the linting task. Looking at the logs, this still runs at around the same time as checking all files.

Yeah, maybe it's not worth it then. There are also other complexities that might cause this to fail, for example, what if you have a pull request which wants to merge branchA into master, where they share some parts of the history? `git diff --name-only --diff-filter=d ${base_rev}...${head_rev}` would probably be wrong.

So, I'd say let's not do this, and let's just remove the TODO.

**Pull request merged**
