### PR TITLE
added the main function to all console_scripts that had a main

### PR DESCRIPTION
**Pull request by abstrekt**
This is my first ever PR, I hope I did everything right, please review :)

### CODE REVIEW

**Comment by abstrekt** [comment]
what is this "Some checks haven’t completed yet
1 expected check
Taskcluster (pull_request) Expected — Waiting for status to be reported"
could someone please explain it to me? or what I have to do to get this PR approved.

Thanks

**Comment by abstrekt** [comment]
idk what is the linting errors??

**Comment by marco-c** [comment]
Unfortunately there was already a PR open doing the same (#936). It looks like that PR missed one script though, so if you want you can update your PR to fix that script (scripts/regressor_finder.py) and I'll merge it.

**Comment by abstrekt** [comment]
thank you <3 very much, this is my first merged PR ever, this is a very motivation boost towards FOSS  conribution :) thank you once again.

**Pull request merged**
