### PR TITLE
Updated zstandard compress and decompress functions

### PR DESCRIPTION
**Pull request by dishvyas**
Added main compress and decompress functions in utils.py and replaced every other function with function calls.

### CODE REVIEW

**Comment by chidauri** [comment]
@dishvyas mate, you want to change the whole repository?

**Comment by dishvyas** [comment]
> @dishvyas mate, you want to change the whole repository?

I updated the changes i made to the files. Why is that happening? Can you help me??

**Comment by chidauri** [comment]
> > @dishvyas mate, you want to change the whole repository?
> 
> I updated the changes i made to the files. Why is that happening? Can you help me??

[https://githowto.com/resolving_conflicts](url)

**Comment by chidauri** [comment]
> > @dishvyas mate, you want to change the whole repository?
> 
> I updated the changes i made to the files. Why is that happening? Can you help me??

[https://githowto.com/resolving_conflicts](url)

**Comment by chidauri** [comment]
> > @dishvyas mate, you want to change the whole repository?
> 
> I updated the changes i made to the files. Why is that happening? Can you help me??

search how to solve merge conflicts in git

**Pull request closed without merging**
