### PR TITLE
Use Ruff for linting and formatting

### LINKED ISSUE #3767: Use Ruff for linting and formatting
Proposal to use[ Ruff ](https://docs.astral.sh/ruff/) for linting and code quality. Due to following reasons:

-  It's faster 
-  Can fix code automatically

### PR DESCRIPTION
**Pull request by effaf**
I have changed the ```.pre-commit-config.yaml``` file to include ruff. 
resolves #3767

### CODE REVIEW

**Comment by marco-c** [comment]
Sorry @effaf, there's already a PR for this at https://github.com/mozilla/bugbot/pull/2335.

**Comment by marco-c** [comment]
Oh sorry @effaf, that was another project! Ignore my earlier message.

**Comment by effaf** [comment]
okay, looking into it now

**Comment by suhaibmujahid** [comment]
@effaf you could replicate https://github.com/mozilla/bugbot/pull/2335 as a starting point

**Comment by effaf** [comment]
Okay, on it

**Comment by effaf** [comment]
I think ruff repo has been included. Let me know if I am missing something

**Comment by suhaibmujahid** [comment]
> @suhaibmujahid I think ruff repo has been included. Let me know if I am missing something. Closing this as of now

@effaf I think there is a misunderstanding. The pull request that adds Ruff (https://github.com/mozilla/bugbot/pull/2335) is in another repo (i.e., BugBot); this repo is BugBug.

The idea is to do the same here in this repo.

**Pull request closed without merging**
