### PR TITLE
Add number of words in summary as a feature

### PR DESCRIPTION
**Pull request by ayush-1506**
Addresses: #1013

### CODE REVIEW

**Comment by marco-c** [comment]
Can you add it to the spam model too and see what the results are before/after?

**Comment by ayush-1506** [comment]
Before changes:
```
X: (75599, 348530), y: (75599,)
Cross Validation scores:
Accuracy: f0.967327515160121 (+/- 0.001821559927450232)
Precision: f0.3998628366869471 (+/- 0.015104623637706024)
Recall: f0.9892278489593925 (+/- 0.01776930062893444)
X_train: (2972, 348530), y_train: (2972,)
X_test: (7560, 348530), y_test: (7560,)
```
After changes:
```
X: (75599, 348531), y: (75599,)
Cross Validation scores:
Accuracy: f0.973456310496038 (+/- 0.0037455635022670586)
Precision: f0.4516030602755977 (+/- 0.03500464607781789)
Recall: f0.990574650306194 (+/- 0.007860111707652969)
X_train: (2972, 348531), y_train: (2972,)
X_test: (7560, 348531), y_test: (7560,)
```

**Comment by marco-c** [comment]
Great, it's a measurable improvement!

Can you update the PR with the spam model changes? Then I'll merge it.

**Comment by marco-c** [comment]
Thanks!

**Pull request merged**
