### PR TITLE
Applying document similarity to bug summaries

### PR DESCRIPTION
**Pull request by chidauri**

### CODE REVIEW

**Comment by marco-c** [comment]
We need a way to evaluate the results, or we can't compare different solutions.

One possibility is to get groups of bugs (each group would be composed of a bug and all bugs that are duplicates of it), and check that the tool would find, for each bug in the group, all other members of the group.

This is not a great measure though because, for a given bug, there could be bugs that were missed by humans but that are actually duplicates of that bug. So, both the recall and precision can't be properly calculated.

Try to do some research and find how other people have approached this, by reading some publications about bug duplicate detection.

If we don't find a better way to measure, then we'll do what I proposed and just assume that the human duplicate detection was perfect.

**Comment by marco-c** [comment]
As discussed on IRC, we'll consider the dataset as being clean (so all duplicates as being really duplicates, and no duplicates outside of those detected by humans).

**Comment by marco-c** [comment]
@chidauri are you still interested in working on this?
I'm going to close the PR otherwise.

**Comment by chidauri** [comment]
@marco-c  i was a little busy, i will continue this.

**Comment by chidauri** [comment]
@marco-c seems like duplicate classifier is already being worked upon , so i can help in that or pick up any other issue, whatever you say, you can close this PR.

**Comment by marco-c** [comment]
@chidauri you could either work on #26, which is similar (but not based on textual features but on other features), or help with #517 (which is the work you started to do in this bug).

**Comment by chidauri** [comment]
@marco-c can't this be used as it is in #517 ? I'll make it return a list of bug ids of top x bugs.

**Comment by marco-c** [comment]
@chidauri yep! We'll also need some code to evaluate the results, as discussed earlier.

**Comment by marco-c** [comment]
TBC in #547.

**Pull request closed without merging**
