### PR TITLE
Move duplicates map inside evaluation method

### PR DESCRIPTION
**Pull request by ayush-1506**
Addresses : #939

### CODE REVIEW

**Comment by marco-c** [comment]
@ayush-1506 this is solving only the second part of that issue, right?

**Comment by ayush-1506** [comment]
@marco-c Yes, the part which consists of running the docker image is taking too much time. Is there a way to run the model in the docker environment but on a reduced set of bugs? (Just to test if the model is being trained)

**Comment by marco-c** [comment]
@ayush-1506 you can simply test by modifying https://github.com/mozilla/bugbug/blob/91db314240bd53f093218c47d5274e54d75f456d/bugbug/similarity.py#L559 to use just a subset of bugs.

**Comment by ayush-1506** [comment]
Oh, I thought I might have to make changes in the dockerfile. Thanks!

**Pull request merged**
