### PR TITLE
fixes #2108: organize charts

### LINKED ISSUE #2108: Organize charts in the summary view in a nicer way
Currently charts take the entire screen width and are positioned one after another vertically, something like https://apexcharts.com/javascript-chart-demos/dashboards/ would be nicer and more readable.

### PR DESCRIPTION
**Pull request by Saffafatima12**
Hi, I am new to bugbug. I tried to arrange the charts in pairs with some spacing as shown below which looks slightly better than single charts one after the other. I think there is a lot of room for further improvement in the UI and I am happy to make further changes if needed for this issue.

I have tried my best to adhere to contribution guidelines, but if there are any mistakes in my pull request, please let me know and I will be happy to correct my code. 

Before:

before

After:

after

### CODE REVIEW

**Comment by marco-c** [comment]
Thanks @Saffafatima12, the screenshot of the changed UI looks definitely better than the original one ;)
Unfortunately it doesn't work on my computer, maybe because of the resolution of my screen (your change only works if I zoom out at 30% level).

> I think there is a lot of room for further improvement in the UI and I am happy to make further changes if needed for this issue.

I agree, feel free to file any improvement you can think of as an issue, then submit a separate PR for each.

> I have tried my best to adhere to contribution guidelines, but if there are any mistakes in my pull request, please let me know and I will be happy to correct my code.

You did adhere correctly ;)

**Comment by Saffafatima12** [comment]
Thank you so much for reviewing my PR. I have tried to modify the styling and it seems to be work when I test it with different screen widths.

screen-capture_Trim

**Comment by marco-c** [comment]
> I have tried to modify the styling and it seems to be working when I test it with different screen widths.

Unfortunately it still doesn't work on my machine, probably because of display scaling (my scaling is set to 300%) rather than just resolution.

**Comment by marco-c** [comment]
@Saffafatima12 do you still intend to work on this?

**Comment by Saffafatima12** [comment]
Ah, apologies for not informing you earlier. I feel that this issue is too advanced for me and I am happy for others to take this up.

**Pull request closed without merging**
