### PR TITLE
Use component and product features in the bug model

### LINKED ISSUE #37: Use 'product' and 'component' features in the models
b7369ea8bf282941ce4b378ad5ad3c832db20668 introduced the features, but we are still not using them.

### PR DESCRIPTION
**Pull request by chidauri**
Fixes #37.

### CODE REVIEW

**Comment by ayush1999** [comment]
The build is failing because of improper indentation. (Run flake8 locally to make sure code is properly styled)

**Comment by marco-c** [comment]
You don't have to open a new PR for every CI failure, you can just update an already existing PR :smile:

**Comment by marco-c** [comment]
Well, you deleted the old one, so I'll reopen this one.

**Comment by Harshit1998** [comment]
Sorry :)

**Comment by chidauri** [comment]
Sorry :)

**Comment by marco-c** [comment]
@chidauri let me know when you update the PR.

**Comment by chidauri** [comment]
@marco-c I,ve updated the PR. On my PC the indentation was correct,how did it change?

**Comment by marco-c** [comment]
> @marco-c I,ve updated the PR. On my PC the indentation was correct,how did it change?

It's still wrong, there are tabs instead of spaces. Probably your text editor is doing this.

**Comment by chidauri** [comment]
Fixed finally, maybe :)

**Pull request merged**
