### PR TITLE
Created a new YAML anchor that includes the common parts

### LINKED ISSUE #268: Merge common parts of .taskcluster.yml
This will make the file more readable.

### PR DESCRIPTION
**Pull request by rajdeep988**
- fixes #268
 **Merging the common parts of code by creating a new YAML anchor that includes the common parts and referencing it using the * alias syntax.**

### CODE REVIEW

**Comment by rajdeep988** [comment]
Could anyone tell how could i fix this?

**Comment by suhaibmujahid** [comment]
> Could anyone tell how could i fix this?

Could you please link to the issue you are fixing and add a description?

It could be helpful to split the changes in commits with smaller diffs and push them one by one. In this way, it will be easier for you to spot where it is failing.

**Comment by rajdeep988** [comment]
Glad you responded!
- Linked to the issue. 
- Added a description.

**Comment by suhaibmujahid** [comment]
Thank you @rajdeep988 for opening this PR. However, issue #268 already has an open PR. Please read #1092.

**Comment by rajdeep988** [comment]
I apologize for the inconvenience. Please guide me on how to proceed with this pull request. Do I need to close it, or is there something else that needs to be done?

**Comment by suhaibmujahid** [comment]
@rajdeep988 I will close this for now. Feel free to reopen it if the other pull request got closed without fixing the issue.

**Pull request closed without merging**
