### PR TITLE
Code formatting of f-strings and set declaration

### PR DESCRIPTION
**Pull request by Jeetu95**
Worked on issues #82  and #81.
 - Changed necessary conversions of lists into sets. #82 
 - Used f-strings everywhere where format() function was used. #81 

@marco-c  Please take a look.
Thank you

### CODE REVIEW

**Comment by marco-c** [comment]
@Jeetu95 each PR should be self-contained and fix only one issue. Could you remove one of the two changes?

**Comment by marco-c** [comment]
You can use the `git rebase` command to edit your history.

**Comment by Jeetu95** [comment]
I created a new branch with only one commit. Can I make a PR from that branch and close this one?

**Comment by marco-c** [comment]
> I created a new branch with only one commit. Can I make a PR from that branch and close this one?

As you prefer, but I think it's good if you learn how to rewrite history, as you will definitely have to do it from time to time.

**Comment by Jeetu95** [comment]
Yes, I am already onto it. But for the timing, I am creating this new PR. #85

**Pull request closed without merging**
