### PR TITLE
Add Blank Metric

### LINKED ISSUE #1482: Add Blank metric
See https://github.com/mozilla/rust-code-analysis/commit/86ac7c967cf70be99ef8d5a138da45b1c4266dca

### PR DESCRIPTION
**Pull request by 1Gokul**
Attempt to fix #1482. 

Please tell me if I've messed up somewhere.

### CODE REVIEW

**Comment by 1Gokul** [comment]
Well :(

**Comment by 1Gokul** [comment]
The bugbug test logs [here](https://community-tc.services.mozilla.com/tasks/P6uOPVR_TK6cmNc7k_s9bg/runs/0/logs/public/logs/live.log) always show a KeyError when using the `metrics` dictonary.

[`obj["blank_total"] += metrics["blank"]["sum"]` on line 508](https://github.com/1Gokul/bugbug/blob/e10c6a654d91ef5cc02c9cef05e4f6e792193e8c/bugbug/repository.py#L508) seems to be causing the error.

Any ideas on how to fix?

**Comment by marco-c** [comment]
@1Gokul there is already another PR about this (#2152), since it is older it has priority. If @Patil2099 abandons #2152, then we can accept this PR.

**Comment by marco-c** [comment]
> Any ideas on how to fix?

Try printing the `metrics` dict, and see if it actually contains a `blank` key.

**Comment by 1Gokul** [comment]
> 
> 
> @1Gokul there is already another PR about this (#2152), since it is older it has priority. If @Patil2099 abandons #2152, then we can accept this PR.

Alright, sure!

**Comment by marco-c** [comment]
The other PR has been abandoned, you can continue this if you want.

**Comment by 1Gokul** [comment]
Alright, thanks! I'll start working on it.

**Comment by marco-c** [comment]
@1Gokul you are not adding the blank metric, but the mi metric again. Maybe the git branch was messed up?

**Comment by 1Gokul** [comment]
I was actually attempting to update my added-blank-metric branch to the latest commit of the original repo.

**Comment by 1Gokul** [comment]
The branch is now updated!

**Comment by 1Gokul** [comment]
All checks have passed! 
Please tell me if I've messed up somewhere.

**Review by marco-c — APPROVED** [review]

**Pull request merged**
