### PR TITLE
Added functions of compression and decompression (zstandard)

### PR DESCRIPTION
**Pull request by dishvyas**
Function Compress and Decompress using Zstandard added

### CODE REVIEW

**Comment by marco-c** [comment]
The goal is to also make use of these functions where the compression/decompression code is currently being used.

**Comment by marco-c** [comment]
Please also use a better commit message / PR name, "Update utils.py" is too generic.

**Comment by marco-c** [comment]
Linting is failing, I suggest using pre-commit to handle linting issues semi-automatically.

**Comment by dishvyas** [comment]
> The goal is to also make use of these functions where the compression/decompression code is currently being used.

I have used the functions in the other files as well. They were about 7-8. Do i need to create a pull request for all of them??

**Comment by marco-c** [comment]
> I have used the functions in the other files as well. They were about 7-8. Do i need to create a pull request for all of them??

No, you can change all of them in this PR.

**Comment by marco-c** [comment]
Closed in favor of #790.

**Pull request closed without merging**
