### PR TITLE
Added Blank Metric

### LINKED ISSUE #1482: Add Blank metric
See https://github.com/mozilla/rust-code-analysis/commit/86ac7c967cf70be99ef8d5a138da45b1c4266dca

### PR DESCRIPTION
**Pull request by Patil2099**
Fixes #1482

### CODE REVIEW

**Comment by Patil2099** [comment]
@marco-c  @Luni-4  Please review my pr. Please let me know if you want any changes. If this goes well. I can work on other metric too.

**Comment by marco-c** [comment]
@Patil2099 there are some test failures, you can see them by clicking on the "Details" link on the right of "Community-TC (pull_request)"

**Comment by Patil2099** [comment]
@marco-c  Can you help me with this and explain what was wrong here? it would be great help but still I will try to do it on my own.

**Comment by marco-c** [comment]
@Patil2099 the first step is checking the link I told you and seeing what the test failure is. Once you know what it is, you can try to run it locally with pytest (`python -m pytest tests/FAILINGTESTHERE`)

**Comment by Luni-4** [comment]
@Patil2099 

Try to follow the `Cloc` example described [here](https://github.com/marco-c/bugbug/commit/96904632fb70d0244ff81b16eee26f338550aec7). It should help fixing tests.

For lints problems instead:
- Add a space after `:`
- Add a `,` after the `]` of an array

**Comment by marco-c** [comment]
For linting problems you can also use pre-commit, which will handle code formatting automatically.

**Comment by marco-c** [comment]
There are still test failures and some linting failures.

The test failure is:
```
>       obj["blank_total"] += metrics["blank"]["sum"]
E       KeyError: 'blank'
```

Try printing the "metrics" object and see if there is a `blank` key or if it's part of a subkey (like sloc, ploc, lloc, etc.).

**Comment by marco-c** [comment]
@Patil2099 do you still intend to continue this?

**Comment by Patil2099** [comment]
Sorry for the late reply. I had a busy week. I would continue to work on this. :) @marco-c

**Comment by marco-c** [comment]
@Patil2099 there's also @1Gokul who wanted to work on this, are you sure you want to continue? It's been a while now :)

**Comment by marco-c** [comment]
Closing for lack of response, feel free to reopen if you still intend to work on this.

**Pull request closed without merging**
