### PR TITLE
Add a main function to all our console_scripts so they are more easily runnable

### LINKED ISSUE #831: Add a main function to all our console_scripts so they are more easily runnable
https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html

We simply need to add:
```Python
if __name__ == "__main__":
    main()
```
at the end of every script.

### PR DESCRIPTION
**Pull request by shishirjha**
Added main function in all the scripts which have main function defined.

Fixes #831

### CODE REVIEW

**Comment by shishirjha** [comment]
Thank you for the review. I am working on it. So, please assign this issue to me.

**Comment by shishirjha** [comment]
Sorry I did not mean to merge it. It was just that my branch was behind the master so I just updated it.

**Comment by marco-c** [comment]
> Sorry I did not mean to merge it. It was just that my branch was behind the master so I just updated it.

That's OK, you just updated your PR :)

**Comment by marco-c** [comment]
> That's OK, you just updated your PR :)

To be clear, you did not merge your PR into master, you merged master into your PR! So, you have just updated your PR to the latest code.

**Comment by shishirjha** [comment]
Hi I am consfused here. Why did it show the task lint as failed? In my systems all tests have passed. I used pre-commit as advised and every tests are passing. But in the log of taskcluster I see that the test of "black" did not pass.  Can anyone help me here. This is my first contribution. Please help me.

**Comment by Lothiraldan** [comment]
Black says that `bugbug/scripts/check.py` is not correctly formatted, maybe it was due to a merge made on Github.

You can launch pre-commit on specific files with: `pre-commit run bugbug/scripts/check.py` and Black should format it for you. Don't forget to commit the modifications in order to fix the build.

**Comment by shishirjha** [comment]
I have made necessary changes. All tests are passing now. please review it now.

**Pull request merged**
