### PR TITLE
Bump python from 3.10.7-slim to 3.11.7-slim in /infra

### PR DESCRIPTION
**Pull request by marco-c**
Bumps python from 3.10.7-slim to 3.11.7-slim.

---
updated-dependencies:
- dependency-name: python dependency-type: direct:production update-type: version-update:semver-minor

### CODE REVIEW

**Comment by marco-c** [comment]
We are not ready yet for 3.12 (see #3920), but maybe we are for 3.11.

**Review by suhaibmujahid — DISMISSED** [review]
Thank you! I installed the dependencies on my Mac M1, everything seems to be working fine.

**Comment by suhaibmujahid** [comment]
We may want to update pre-commit as well:

https://github.com/mozilla/bugbug/blob/6631ba167ea7d55508f05b3fc962fedc88e0d105/.pre-commit-config.yaml#L95-L96

**Review by suhaibmujahid — DISMISSED** [review]

**Comment by suhaibmujahid** [comment]
Note: the changes in `.taskcluster.yml` will cause conflicts in https://github.com/mozilla/bugbug/pull/4014.

**Comment by marco-c** [comment]
I will wait for that one to land first before merging this

**Comment by suhaibmujahid** [comment]
> I will wait for that one to land first before merging this

@marco-c I just merged #4014. Could you please rebase?

**Pull request merged**
