### PR TITLE
Remove pip from the commit retrieval image

### LINKED ISSUE #647: Remove pip from the commit-retrieval image
We are installing pip2 to install mercurial. We should be able to, in a single layer, install pip2, install mercurial, then remove pip2 and clean. This should sliglthy reduce the image size.

### PR DESCRIPTION
**Pull request by trampfox**
As per title, this PR fixes #647.

### CODE REVIEW

**Comment by marco-c** [comment]
Could you try running the `scripts/commit_retriever.py` script in a Docker container with this image to make sure it still works? (to run the script, you can just create a Docker container with this image and run `bugbug-data-commits .`)

**Comment by trampfox** [comment]
@marco-c I tried to run the following command 
```
docker run mozilla/bugbug-commit-retrieval:latest bugbug-data-commits .
```
and this is the output returned by the script
```
INFO:bugbug.repository:mozilla-central cloned
INFO:bugbug.repository:Pulling and updating mozilla-central
INFO:bugbug.repository:mozilla-central pulled and updated
Downloading https://index.taskcluster.net/v1/task/project.relman.bugbug.data_commits.latest/artifacts/public/commits.json.version to data/commits.json.version
Downloading https://index.taskcluster.net/v1/task/project.relman.bugbug.data_commits.latest/artifacts/public/commits.json.zst to data/commits.json.zst
Downloading https://index.taskcluster.net/v1/task/project.relman.bugbug.data_commits.latest/artifacts/public/commit_experiences.pickle.zst to data/commit_experiences.pickle.zst
Getting revs from children(cffdfed81a70f820dcec61752edcf6349e583aba) to tip...
Mining 187 commits using 5 processes...
100%|██████████| 1/1 [00:07<00:00,  7.24s/it]
100%|██████████| 187/187 [00:00<00:00, 69477.80it/s]
100%|██████████| 187/187 [00:00<00:00, 971.76it/s] Downloading file->component mapping...
90 commits to ignore
Analyzing experiences from 187 commits...
Mining 97 commits using 5 processes...

100%|██████████| 97/97 [00:07<00:00, 12.38it/s]
INFO:scripts.commit_retriever:commit data extracted from repository
```
Is should be ok, right? 
To get it work, I had to remove the `apt-get autoremove` command.

**Comment by marco-c** [comment]
What was the problem when you had "autoremove"?
Maybe we could install the necessary packages which are actually required and we are not explicitly installing, then uninstall python-pip and then run "autoremove".

**Comment by trampfox** [comment]
Running the `apt-get autoremove` command I got the following error: 
```

**Comment by trampfox** [comment]
Running the `apt-get autoremove` command I got the following error
```
Traceback (most recent call last):
  File "/usr/local/bin/bugbug-data-commits", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/scripts/commit_retriever.py", line 60, in main
    retriever.retrieve_commits()
  File "/usr/local/lib/python3.7/site-packages/scripts/commit_retriever.py", line 23, in retrieve_commits
    repository.clone(self.repo_dir)
  File "/usr/local/lib/python3.7/site-packages/bugbug/repository.py", line 769, in clone
    proc = hglib.util.popen(cmd)
  File "/usr/local/lib/python3.7/site-packages/hglib/util.py", line 241, in popen
    startupinfo=startupinfo, env=environ)
  File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hg': 'hg'
```
Looking at the list of the packages that are going to be removed by this command, I noticed that also the `python` package was removed, which probably is needed in order to run mercurial(?). 
So, I tried to exclude the `python` package from the `autoremove` package list using the `apt-mark` command. 
I added the following command to the Dockerfile (before the `purge` and the `autoremove`)
```
apt-mark manual python
```
which marks the package as manually installed and `autoremove` won't remove it. 
This could be a good solution in order to actually remove all the unneeded packages.

**Comment by marco-c** [comment]
I wonder if you couldn't achieve the same by replacing `apt-get install -y python-pip git` with `apt-get install -y python python-pip git`.

**Comment by trampfox** [comment]
Yes, I tried running it again without the `apt-mark` command and with the `python` package in the `apt-get install`. It worked. 
I'm going to fix the linting issues.

**Comment by trampfox** [comment]
Done :) 
```
seed isort known_third_party.............................................Passed
isort....................................................................Passed
black....................................................................Passed
flake8...................................................................Passed
Trim Trailing Whitespace.................................................Failed
hookid: trailing-whitespace

Files were modified by this hook. Additional output:

Fixing infra/dockerfile.commit_retrieval

Check Yaml...............................................................Passed
Mixed line ending........................................................Passed
Tests should end in _test.py.............................................Passed
Check JSON...............................................................Passed
codespell................................................................Passed
taskcluster_yml..........................................................Passed
Check hooks apply to the repository......................................Passed
Check for useless excludes...............................................Passed
```

**Comment by marco-c** [comment]
Unfortunately the commit_retriever.py script succeeds, but the commit_classifier.py fails :(
I'll have to revert this.

**Comment by marco-c** [comment]
Actually it was an unrelated error, so I'm reverting the revert :)

**Pull request merged**
