### PR TITLE
adding test for component model

### LINKED ISSUE #433: Add basic tests for component model

### PR DESCRIPTION
**Pull request by Abhi-khandelwal**
Fix #433

### CODE REVIEW

**Comment by Abhi-khandelwal** [comment]
How can I run tests?

**Comment by marco-c** [comment]
`python3 -m pytest tests/test_component.py`

You should try not to submit PRs when you are not sure if they work or not.

**Comment by Abhi-khandelwal** [comment]
Ohk @marco-c it won't be happen again :)

**Comment by marco-c** [comment]
No problem, I know these are your first contributions.

**Comment by Abhi-khandelwal** [comment]
Yup thanks for understanding, So when I try to test this file , it shows `AssertionError: There should be at least one bug matching Core::IPC` at L-166 in models/component.py

**Comment by kanurag94** [comment]
> Yup thanks for understanding, So when I try to test this file , it shows `AssertionError: There should be at least one bug matching Core::IPC` at L-166 in models/component.py

You need to have the id you are running match in mock DB tests/fixtures/bugs.json as well as data/bugs.json. Also make sure you are using correct ids not just random ids from other tests or json.

**Comment by Abhi-khandelwal** [comment]
@kanurag94 How would I find the correct id in tests/fixtures/bugs.json file ?

**Comment by kanurag94** [comment]
@Abhi-khandelwal You should look at the bugbug/models/component.py and see which ids it is picking up.
Include those in your tests and make sure they exist on both bugs.json

Workaround: You can debug component.py and print the ids to know for sure what is working.
Submit your commit only when `pytest -m tests/test_* returns 0 failures`

**Comment by marco-c** [comment]
> Yup thanks for understanding, So when I try to test this file , it shows AssertionError: There should be at least one bug matching Core::IPC at L-166 in models/component.py

@Abhi-khandelwal fixing issues requires a bit of investigation to understand the pre-existing code, to try out things, and so on. If I tell you directly how to fix an issue, you won't learn anything.

**Comment by marco-c** [comment]
Closing for inactivity, but feel free to reopen if you still intend to work on this.

**Pull request closed without merging**
