### PR TITLE
'Is reporter a Mozillian' as a feature #30

### LINKED ISSUE #30: 'Is reporter a Mozillian' as a feature
The first implementation will simply check if an email contains "@mozilla.com" or "@mozilla.org".

### PR DESCRIPTION
**Pull request by poojan124**
Fixes #30 I have updated the code from #86. Please review this PR.

### CODE REVIEW

**Comment by marco-c** [comment]
@poojan124 when you update the code, you should update the PR, not close it and open a new one.

**Comment by poojan124** [comment]
@marco-c Yes sorry about that. 
Why CI failing for this update?

**Comment by marco-c** [comment]
> Why CI failing for this update?

It's #91, unrelated to your changes.

**Comment by poojan124** [comment]
@marco-c I can add test for this in test_bug_features.py.

**Comment by marco-c** [comment]
@poojan124 yes, please! Forgot to ask for it :)

**Comment by poojan124** [comment]
@marco-c  Ok just to clarify few things.
1. I need to create new test file `is_mozillian.json` under `test/fixtures/bug_features/`.
2. To push these changes I will open new PR right?

**Pull request merged**
