### PR TITLE
Rollback assignee change

### PR DESCRIPTION
**Pull request by LakshyAAAgrawal**
Added rollback function to AssigneeModel and used it for rollback in Bug Feature Extraction Using BugExtractor.
Refer https://github.com/mozilla/bugbug/pull/204#discussion_r262426790

### CODE REVIEW

**Comment by LakshyAAAgrawal** [comment]
Hey, the output of AssigneeModel.train() is attached in [text_out.txt](https://github.com/mozilla/bugbug/files/2948106/text_out.txt)

**Comment by marco-c** [comment]
Could you post the average precision/recall values before/after this change?

**Comment by LakshyAAAgrawal** [comment]
Hey,
Will something like [this](https://stackoverflow.com/a/31587532) need to be implemented, or is there some in-built way to print the required information?

**Comment by marco-c** [comment]
The required information is already printed, it is a subset of what you attached here.

**Comment by LakshyAAAgrawal** [comment]
After Change

| No Confidence Threshold > than | Precision | Recall |
|-----------------------------------------|-------------|----------|
\- | 0.56 | 0.56 |
0.6 | 0.87 | 0.87 |
0.7 | 0.89 | 0.90 |
0.8 | 0.93 | 0.94 |
0.9 | 0.96 | 0.97 |

**Comment by LakshyAAAgrawal** [comment]
I will post the results without rollback in a few hours.

**Comment by marco-c** [comment]
It's surprising that it got better, we have removed information, I was thinking it would get worse.

**Comment by LakshyAAAgrawal** [comment]
Should I report back with more testing and data? If yes, what?

**Comment by marco-c** [comment]
No this is OK ;)

**Pull request merged**
